### ISSUE TITLE
Ändern von Gruppen/Usern

### ISSUE THREAD

**Issue by berse2212** [Matthias1994/Projekt-Urlaubsplaner#21]
Man kann eine Gruppe bzw. User einmal ändern und abspeichern. Diese Änderung wird übernommen. Wenn man es ein zweites Mal bei der selben Gruppe oder dem selben User versucht wird die Veränderung nicht mehr gespeichert

**Comment by Matthias1994** [comment]
Fix - bitte die Datenbank vom Git herunterladen!
